blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a question or get help
    url: https://github.com/jnilo1/silvercrest-gateway-hacking/discussions
    about: Please use GitHub Discussions for usage questions or support requests.
